blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',
        views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
        views.post_detail,
        name='post_detail'),
    path('<int:post_id>/comment/', 
        views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

halal/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

"""
Create a custom manager for Post model that allows retrieving posts by status
"""
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)



"""
Post model
"""
class Post(models.Model):

    """
    Status class that defines the status of a Post, either published or in draft
    """
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='blog/', blank=True, null=True)
    status = models.CharField(max_length=2, 
                            choices=Status.choices, 
                            default=Status.DRAFT)

    """
    Initializing the managers
    """
    objects = models.Manager() # Default manager
    published = PublishedManager() # Our custom manager
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    """
    Overide the get_absolute_url method to dynamically build the url
    """
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])
    tags = TaggableManager()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

        def __str__(self):
            return f"Comment by {self.name} on {self.post}"

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, SearchForm
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity

# Create your views here.

"""
Create FBV for retrieving all the published posts
"""
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 4)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',
    {'posts': posts,
    'tag': tag})

"""
Create FBV for retrieving a single post
"""
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, 
                            status=Post.Status.PUBLISHED, 
                            slug=post, 
                            publish__year=year, 
                            publish__month=month, 
                            publish__day=day)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # List of similar posts
    posts_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=posts_tags_ids)\
                                    .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                    .order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', 
    {'post': post,
    'comments': comments,
    'form': form,
    'similar_posts': similar_posts})

"""
 Create FBV for adding comment
"""
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html',
                            {'post': post,
                            'form': form,
                            'comment': comment})

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    
    return render(request,
                'blog/post/search.html',
                {'form': form,
                'query' : query,
                'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/ico"
      href="{% static 'img/favicon.ico' %}"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</head>
<header>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a href="/blog/" class="navbar-brand">
                <h3>HAC TV Blog</h3>
                <small>Halal Arabic Course TV</small>
            </a>
            <form action="{% url 'blog:post_search' %}" method="get">
                <div class="input-group">
                    <input type="text" name="query" id="id_query" required class="form-control" placeholder="Search"
                        aria-label="Search">
                    <button type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-search" viewBox="0 0 16 16">
                            <path
                                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </nav>
</header>

<body>
    <div class="container-fluid">
            {% block content %}
            {% endblock %}
        <h3>Most commented posts</h3>
        <div class="row  row-cols-auto justify-content-lg-start justify-content-center">
            {% get_most_commented_posts as most_commented_posts %}
            {% for post in most_commented_posts %}
            <div class="col">
                <div class="card">
                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                    <div class="card-body">
                        <h1 class="card-title">
                            {{ post.title }}
                        </h1>
                        <small class="date">
                            Published {{ post.publish }} {{ post.author }}
                        </small>
                        <a class="stretched-link" href="{{ post.get_absolute_url }}">
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% show_latest_posts 3 %}
    </div>
</body>
<footer>
    <nav class="navbar bg-body-secondary">
        <div class="footer-container container-fluid">
            <ul class="nav">
                <li class="nav-item">
                    <a href="/blog/" class="footer-navbar-brand navbar-brand">
                        <h4>HAC TV</h4>
                    </a>
                    <small>&copy; 2023 HAC TV. All Rights Reserved.</small>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                            fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                            <path
                                d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" />
                        </svg></a>
                </li> -->
            </ul>
            <a href="{% url 'blog:post_feed' %}">
                RSS feed
            </a>
        </div>
    </nav>
</footer>

</html>

blog/templates/blog/pagination.html
<div class="pagination">
    <nav aria-label="Pagination">
        <ul class="pagination">
        {% if page.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
</div>

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to post</a></p>
    {% else %}
        {% include 'blog/post/includes/comment_form.html' %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<hr>
<div class="post-image">
    <img src="{{ post.image.url }}" alt="{{ post.title }}" />
</div>
<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
{{ post.body|markdown }}
<div class="similar-posts">
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <a href="{{ post.get_absolute_url}}">
        <div class="container">
            <div class="row row-cols-auto g-0 align-items-center">
                <div>
                    <img width="100px" height="100px" src="{{ post.image.url }}" alt="{{ post.title }}">
                </div>
                <div class="similar-post-title">
                    <h1>{{ post.title }}</h1>
                </div>
            </div>
        </div>
    </a>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}
</div>
<section id="comment-section">
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}
    {% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
    {% endfor %}
    {% include 'blog/post/includes/comment_form.html' %}
</section>
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
    <form class="comment-form" action="{% url 'blog:post_comment' post.id %}" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>

blog/templates/blog/post/latest_posts.html
<h1>Latest Posts</h1>
<div class="row row-cols-auto justify-content-lg-start justify-content-center">
    {% for post in latest_posts %}
    <div class="col">
        <div class="card">
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
                <div class="card-body">
                    <h1 class="card-title">
                        {{ post.title }}
                   </h1>
                    <small class="date">
                        Published {{ post.publish }} {{ post.author }}
                    </small>
                    <a class="stretched-link"  href="{{ post.get_absolute_url }}">
                    </a>
                </div>
        </div>
    </div>
    {% endfor %}
</div>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Halal Blog{% endblock %}</title>
</head>

<body>
    {% block content %}
    <div class="row row-cols-auto justify-content-lg-start justify-content-center">
        {% for post in posts %}
        <div class="col">
            <div class="card">
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
                <div class="card-body">
                    <h1 class="card-title">
                        {{ post.title }}
                    </h1>
                    <small class="date">
                        Published {{ post.publish }} {{ post.author }}
                    </small>
                    <a class="stretched-link" href="{{ post.get_absolute_url }}">
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="page col-12">{% include 'blog/pagination.html' with page=posts %}</div>
    </div>
    {% endblock %}
</body>

</html>

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <hr>
        <h3>
            {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
            <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
        {% endfor %}
    {% else %}
            <h1>Search for posts</h1>
            <hr>
            <form method="get">
                {{ form.as_p }}
                <input type="submit" value="Search">
            </form>
    {% endif %}
{% endblock %}